version: '3'
services:
  db: # Database implementation, in this case MySQL
    image: mysql:5.7
    container_name: seek-mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    stop_grace_period: 1m30s
    env_file:
      - docker/db.env
    volumes:
      - seek-mysql-db:/var/lib/mysql

  seek: # The SEEK application
    #build: .

    image: fairdom/seek:main

    container_name: seek
    command: docker/entrypoint.sh
    restart: always
    environment:
      RAILS_ENV: production
      SOLR_PORT: 8983
      SOLR_HOST: solr
      NO_ENTRYPOINT_WORKERS: 1
    env_file:
      - docker/db.env
    volumes:
      - seek-filestore:/seek/filestore
      - seek-cache:/seek/tmp/cache
    ports:
      - "3000:3000"
    depends_on:
      - db
      - solr
      - mail
    links:
      - db
      - solr
      - mail

  seek_workers: # The SEEK delayed job workers
      #build: .

      image: fairdom/seek:main
      container_name: seek-workers
      command: docker/start_workers.sh
      restart: always
      environment:
        RAILS_ENV: production
        SOLR_PORT: 8983
        SOLR_HOST: solr
      env_file:
        - docker/db.env
      volumes:
        - seek-filestore:/seek/filestore
        - seek-cache:/seek/tmp/cache
      depends_on:
        - db
        - solr
        - mail
      links:
        - db
        - solr
        - mail

  solr:
    image: fairdom/seek-solr:8.11
    container_name: seek-solr
    restart: always
    environment:
      SOLR_JAVA_MEM: -Xms512m -Xmx1024m
    volumes:
      - seek-solr-data:/var/solr/
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - seek
      - /opt/solr/server/solr/configsets/seek_config

  mail:
    image: eeacms/postfix
    environment:
      MTP_HOST: fair-dom.org

volumes:
  seek-filestore:
    external: true
  seek-mysql-db:
    external: true
  seek-solr-data:
    external: true
  seek-cache:
    external: true
