FROM ruby:2.7-buster

LABEL maintainer="Stuart Owen <orcid.org/0000-0003-2130-0865>, Finn Bacall"
ARG SOURCE_COMMIT
ENV APP_DIR /seek
ENV USER_ID 1001

# need to set the locale, otherwise some gems file to install
ENV LANG="en_US.UTF-8" LANGUAGE="en_US:UTF-8" LC_ALL="C.UTF-8"

RUN useradd -u $USER_ID seekdev && \
    mkdir /home/seekdev && \
    chown -R seekdev:seekdev /home/seekdev

RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends build-essential cmake gettext graphviz git \
		libcurl4-gnutls-dev libmagick++-dev libpq-dev libreadline-dev \
		libreoffice libsqlite3-dev libssl-dev libxml++2.6-dev \
		libxslt1-dev locales default-mysql-client nginx nodejs openjdk-11-jdk-headless \
		python3.7-dev python3.7-distutils python3-pip \
		poppler-utils postgresql-client shared-mime-info sqlite3 links telnet vim zip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    locale-gen en_US.UTF-8

RUN mkdir -p $APP_DIR

USER seekdev

WORKDIR $APP_DIR

# Bundle install throw errors if Gemfile has been modified since Gemfile.lock
COPY Gemfile* ./
RUN bundle install

# App code
COPY . .

USER root
RUN mkdir log tmp
RUN chown -R $USER_ID log tmp
USER seekdev


# Python dependencies from requirements.txt
ENV PATH="/var/www/.local/bin:$PATH"
RUN python3.7 -m pip install setuptools==58
RUN python3.7 -m pip install -r requirements.txt


# Network
EXPOSE 3000

# Shared
VOLUME ["/seek/"]

CMD ["docker/entrypoint.sh"]
