source 'https://rubygems.org'

gem 'rails', '7.2.3'

gem 'abbrev'
gem 'active_model_serializers'
gem 'activerecord-import'
gem 'activerecord-session_store'
gem 'acts-as-taggable-on'
gem 'addressable'
gem 'api_smith', git: 'https://github.com/youroute/api_smith.git', ref: '1fb428cebc17b9afab25ac9f809bde87b0ec315b' #necessary for newer hashie dependency, original api_smith is no longer active
gem 'attr_encrypted'
gem 'auto_strip_attributes'
gem 'bibtex-ruby'
gem 'bio'
gem 'bioportal', git: 'https://github.com/SysMO-DB/bioportal.git'
gem 'bives'
gem 'bootsnap', require: false
gem 'bootstrap-sass'
gem 'bundler'
gem 'caxlsx'
gem 'caxlsx_rails'
gem 'cff'
gem 'citeproc-ruby'
gem 'coffee-rails'
gem 'commonmarker'
gem 'country_select'
gem 'csl-styles'
gem 'csv'
gem 'redis', '~> 5.0'
gem 'sidekiq', '~> 7.0'
gem 'docsplit', git: 'https://github.com/documentcloud/docsplit.git'
gem 'doorkeeper'
gem 'dotenv-rails'
gem 'equivalent-xml'
gem 'exception_notification'
gem 'factory_bot'
gem 'feedjira'
gem 'fleximage', git: 'https://github.com/SysMO-DB/fleximage.git'
gem 'gitlab_omniauth-ldap'
gem 'google-analytics-rails'
gem 'handlebars_assets'
gem 'html-pipeline'
gem 'i18n-js', '~> 3.9.2' # Version 4+ does not support the asset pipeline
gem 'indefinite_article'
gem 'jbuilder'
gem 'jbuilder-json_api'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'json-schema'
gem 'libreconv'
gem 'libxml-ruby', require: 'libxml'
gem 'licensee'
gem 'linkeddata'
gem 'lograge'
gem 'loofah'
gem 'mechanize'
gem 'metainspector'
gem 'mimemagic'
gem 'mutex_m'
gem 'mysql2'
gem 'net-ftp'
gem 'nkf'
gem 'nokogiri'
gem 'observer'
gem 'omniauth'
gem 'omniauth-github'
gem 'omniauth-rails_csrf_protection'
gem 'omniauth_openid_connect'
gem 'open4'
gem 'openid_connect'
gem 'openseek-api'
gem 'pg'
gem 'private_address_check'# Rails 5 upgrade
gem 'progress_bar'
gem 'psych'
gem 'puma'
gem 'rack', '< 3.0.0' # Rack >= 3 causes errors when running functional tests that call multiple actions in a single test
gem 'rack-attack'
gem 'rack-cors', require: 'rack/cors'
gem 'rails-html-sanitizer'
gem 'rails-observers'
gem 'rails_autolink'
gem 'rdf-virtuoso'
gem 'RedCloth'
gem 'rdoc'
gem 'recaptcha'
gem 'remotipart'
gem 'request_store'
gem 'responders'
gem 'rest-client'
gem 'rfc-822'
gem 'rmagick'
gem 'ro-bundle'
gem 'ro-crate'
gem 'rspec-rails'
gem 'rubyzip'
gem 'rugged'
gem 'sample-template-generator'
gem 'sass-rails'
gem 'seedbank'
gem 'simple-spreadsheet-extractor'
gem 'sitemap_generator'
gem 'sprockets-rails'
gem 'sqlite3'
gem 'sunspot_rails'
gem 'terrapin'
gem 'terser'
gem 'uuid'
gem 'validate_url'
gem 'whenever', require: false
gem 'will_paginate'
gem 'yaml_db'
gem 'zenodo-client', git: 'https://github.com/seek4science/zenodo-client.git'

group :production do
  gem 'passenger'
end

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'flamegraph'
  gem 'gem-licenses'
  gem 'listen'
  gem 'pry'
  gem 'pry-doc'
  gem 'pry-remote'
  gem 'rack-mini-profiler'
  gem 'rails_best_practices'
  gem 'request-log-analyzer'
  gem 'rubocop', require: false
  gem 'ruby-prof'
  gem 'stackprof'
  gem 'web-console'
end

group :test do
  gem 'database_cleaner'
  gem 'minitest', '~> 5.4'
  gem 'minitest-reporters'
  gem 'rails-controller-testing'
  gem 'rails-perftest'
  gem 'simplecov'
  gem 'sunspot_matchers'
  gem 'test-prof'
  gem 'vcr'
  gem 'webdrivers'
  gem 'whenever-test'
end

group :test, :development do
  gem 'magic_lamp'
  gem 'teaspoon'
  gem 'teaspoon-mocha'
  gem 'webmock'
end

gem "minitar"
gem "bzip2-ffi"
gem "seven-zip", require: 'seven_zip_ruby'
gem "ruby-xz", require: 'xz'
