#DO NOT EDIT THIS FILE.
#TO MODIFY THE DEFAULT SETTINGS, COPY seek_local.rb.pre to seek_local.rb AND EDIT THAT FILE INSTEAD

require 'bio'
require 'will_paginate'
require 'sunspot_rails'
require 'mimemagic'
require 'omniauth-ldap'
require 'recaptcha'
require 'uuid'
require 'libreconv'
require 'extensions/secret_key_base'

Rails.configuration.after_initialize do
  require 'extensions/object'
  require 'extensions/array'
  require 'extensions/bio'
  require 'extensions/private_address_check_monkeypatch'
  require 'extensions/string'


  SEEK::Application.configure do
    ASSET_ORDER = ['Person', 'Programme', 'Project', 'Institution', 'Investigation', 'Study', 'ObservationUnit', 'Assay', 'Strain', 'DataFile', 'Model', 'Sop', 'Publication', 'Presentation','SavedSearch', 'Organism', 'HumanDisease', 'Event']

    begin
      Seek::Config.propagate_all
    rescue Settings::DecryptionError
      puts "\n" * 3
      puts "#" * 40
      puts
      puts "WARNING - Could not decrypt settings!"
      puts
      puts "Please check the encryption key (filestore/attr_encrypted/key) is"
      puts "is present and is the same key used to encrypt the settings originally."
      puts
      puts "If you no longer have access to the original key you can clear any encrypted"
      puts "settings by running: rake seek:clear_encrypted_settings"
      puts
      puts "#" * 40
      puts "\n" * 3
    end

    Annotations::Config.attribute_names_to_allow_duplicates.concat(["tag"])
    Annotations::Config.versioning_enabled = false

    ENV['LANG'] = 'en_US.UTF-8'

    begin
      if ActiveRecord::Base.connection.data_source_exists?'delayed_jobs'
        # OpenbisFakeJob.create_initial_jobs
        # OpenbisGarbageJob.create_initial_jobs
      end
    rescue Exception=>e
      Rails.logger.error "Error creating default delayed jobs - #{e.message}"
    end
  end
end
