apiVersion: v1
kind: Secret
metadata:
  name: {{ include "seek.db.secretName" . }}
  labels:
    {{- include "seek.labels" . | nindent 4 }}
type: Opaque
data:
  root-password: {{ .Values.mysql.auth.rootPassword | b64enc | quote }}
  password: {{ .Values.mysql.auth.password | b64enc | quote }}
