apiVersion: v1
kind: Service
metadata:
  name: {{ include "seek.fullname" . }}-mysql
  labels:
    {{- include "seek.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
  selector:
    {{- include "seek.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
