production:
  uri: http://virtuoso:8890/sparql
  update_uri: http://virtuoso:8890/sparql-auth

  username: dba
  password: <%= ENV["DBA_PASSWORD"] %>

  private_graph: ENV["RDF_PRIVATE_GRAPH"]
  public_graph: ENV["RDF_PUBLIC_GRAPH"]

  disabled: <%= !ENV["VIRTUOSO"].present? %>