#change settings where appropriate, and then save as virtuoso_settings.yml

production:
  disabled: true

  uri: http://localhost:8890/sparql
  update_uri: http://localhost:8899/sparql-auth

  username: seek_dev
  password: seek_dev99

  private_graph: seek:private
  public_graph: seek:public

development:
  #if disabled is missing, the default is setting false.
  disabled: false

  uri: http://localhost:8890/sparql
  update_uri: http://localhost:8899/sparql-auth

  username: dba
  password: dba99

  private_graph: seek-development:private
  public_graph: seek-development:public

test:
  #if disabled is missing, the default is setting false.
  disabled: false

  uri: http://localhost:8890/sparql
  update_uri: http://localhost:8899/sparql-auth

  username: dba
  password: dba99

  private_graph: seek-testing:private
  public_graph: seek-testing:public