#!/usr/bin/env ruby

require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config', 'environment'))
require File.expand_path(File.join(File.dirname(__FILE__), '..', 'vendor', 'plugins','nailgun','lib','nailgun.rb'))
Nailgun::NailgunServer.new(ARGV).daemonize
