#!/usr/bin/env ruby

require 'rubygems'
require 'daemons'
require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config', 'environment'))

#this should be changed to the specific watcher implmentation for your rdf triple store
#see Seek::Rdf::RdfWatcher for more details

WATCHER_CLASS = Seek::Rdf::VirtuosoRdfWatcher

pid_dir = File.join(Rails.root,"tmp","pids")
FileUtils.mkdir_p(pid_dir) if !File.exists?(pid_dir)

#Daemons.run_proc("watch_rdf",{:dir=>pid_dir,:dir_mode=>:normal}) do
    WATCHER_CLASS.new(ARGV).start
#end
