require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe DataSharePacksController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # DataSharePack. As you add validations to DataSharePack, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DataSharePacksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all data_share_packs as @data_share_packs" do
      data_share_pack = DataSharePack.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:data_share_packs)).to eq([data_share_pack])
    end
  end

  describe "GET #show" do
    it "assigns the requested data_share_pack as @data_share_pack" do
      data_share_pack = DataSharePack.create! valid_attributes
      get :show, {:id => data_share_pack.to_param}, valid_session
      expect(assigns(:data_share_pack)).to eq(data_share_pack)
    end
  end

  describe "GET #new" do
    it "assigns a new data_share_pack as @data_share_pack" do
      get :new, {}, valid_session
      expect(assigns(:data_share_pack)).to be_a_new(DataSharePack)
    end
  end

  describe "GET #edit" do
    it "assigns the requested data_share_pack as @data_share_pack" do
      data_share_pack = DataSharePack.create! valid_attributes
      get :edit, {:id => data_share_pack.to_param}, valid_session
      expect(assigns(:data_share_pack)).to eq(data_share_pack)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new DataSharePack" do
        expect {
          post :create, {:data_share_pack => valid_attributes}, valid_session
        }.to change(DataSharePack, :count).by(1)
      end

      it "assigns a newly created data_share_pack as @data_share_pack" do
        post :create, {:data_share_pack => valid_attributes}, valid_session
        expect(assigns(:data_share_pack)).to be_a(DataSharePack)
        expect(assigns(:data_share_pack)).to be_persisted
      end

      it "redirects to the created data_share_pack" do
        post :create, {:data_share_pack => valid_attributes}, valid_session
        expect(response).to redirect_to(DataSharePack.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved data_share_pack as @data_share_pack" do
        post :create, {:data_share_pack => invalid_attributes}, valid_session
        expect(assigns(:data_share_pack)).to be_a_new(DataSharePack)
      end

      it "re-renders the 'new' template" do
        post :create, {:data_share_pack => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested data_share_pack" do
        data_share_pack = DataSharePack.create! valid_attributes
        put :update, {:id => data_share_pack.to_param, :data_share_pack => new_attributes}, valid_session
        data_share_pack.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested data_share_pack as @data_share_pack" do
        data_share_pack = DataSharePack.create! valid_attributes
        put :update, {:id => data_share_pack.to_param, :data_share_pack => valid_attributes}, valid_session
        expect(assigns(:data_share_pack)).to eq(data_share_pack)
      end

      it "redirects to the data_share_pack" do
        data_share_pack = DataSharePack.create! valid_attributes
        put :update, {:id => data_share_pack.to_param, :data_share_pack => valid_attributes}, valid_session
        expect(response).to redirect_to(data_share_pack)
      end
    end

    context "with invalid params" do
      it "assigns the data_share_pack as @data_share_pack" do
        data_share_pack = DataSharePack.create! valid_attributes
        put :update, {:id => data_share_pack.to_param, :data_share_pack => invalid_attributes}, valid_session
        expect(assigns(:data_share_pack)).to eq(data_share_pack)
      end

      it "re-renders the 'edit' template" do
        data_share_pack = DataSharePack.create! valid_attributes
        put :update, {:id => data_share_pack.to_param, :data_share_pack => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested data_share_pack" do
      data_share_pack = DataSharePack.create! valid_attributes
      expect {
        delete :destroy, {:id => data_share_pack.to_param}, valid_session
      }.to change(DataSharePack, :count).by(-1)
    end

    it "redirects to the data_share_packs list" do
      data_share_pack = DataSharePack.create! valid_attributes
      delete :destroy, {:id => data_share_pack.to_param}, valid_session
      expect(response).to redirect_to(data_share_packs_url)
    end
  end

end
